#@ load("@ytt:data", "data")

#@ def labels():
primes-dev: ""
app: "primes-dev"
service: primes-dev
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: #@ data.values.namespace
  name: primes-dev
spec:
  ports:
  - port: #@ data.values.svc_port
    protocol: TCP
    targetPort:  #@ data.values.app_port
    name: primes-port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: #@ data.values.namespace
  name: primes-dev
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: primes-dev
        image: warroyo90/primes:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
        ports:
          - containerPort: 8080
            name: primes-port
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 60
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health
          initialDelaySeconds: 15
        env:
        - name: WAVEFRONT_APPLICATION_NAME
          value: primes-dev
        - name: WAVEFRONT_APPLICATION_SERVICE
          value: primes
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          value: #@ data.values.wavefront_proxy_url
